openapi: 3.2.0
info:
  description: This is the ToolHive API server.
  title: ToolHive Logs API
  version: '1.0'
tags:
- name: Logs
paths:
  /api/v1beta/workloads/{name}/logs:
    get:
      description: Retrieve at most 1000 lines of logs for a specific workload by name.
      parameters:
      - description: Workload name
        in: path
        name: name
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            text/plain:
              schema:
                type: string
          description: Logs for the specified workload
        '400':
          content:
            text/plain:
              schema:
                type: string
          description: Invalid workload name
        '404':
          content:
            text/plain:
              schema:
                type: string
          description: Not Found
      summary: Get logs for a specific workload
      tags:
      - Logs
      operationId: getApiV1betaWorkloadsByNameLogs
      x-operation-id-source: derived
  /api/v1beta/workloads/{name}/proxy-logs:
    get:
      description: Retrieve at most 1000 lines of proxy logs for a specific workload by name from the file system.
      parameters:
      - description: Workload name
        in: path
        name: name
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            text/plain:
              schema:
                type: string
          description: Proxy logs for the specified workload
        '400':
          content:
            text/plain:
              schema:
                type: string
          description: Invalid workload name
        '404':
          content:
            text/plain:
              schema:
                type: string
          description: Proxy logs not found for workload
      summary: Get proxy logs for a specific workload
      tags:
      - Logs
      operationId: getApiV1betaWorkloadsByNameProxyLogs
      x-operation-id-source: derived
externalDocs:
  description: ''
  url: ''
