openapi: 3.2.0
info:
  description: This is the ToolHive API server.
  title: ToolHive Version API
  version: '1.0'
tags:
- name: Version
paths:
  /api/v1beta/version:
    get:
      description: Returns the current version of the server
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pkg_api_v1.versionResponse'
          description: OK
      summary: Get server version
      tags:
      - Version
      operationId: getApiV1betaVersion
      x-operation-id-source: derived
components:
  schemas:
    pkg_api_v1.versionResponse:
      properties:
        version:
          type: string
      type: object
externalDocs:
  description: ''
  url: ''
